version: "3.8"

services:
  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    networks:
      - app-network

  backend:
    build: ./back-end
    container_name: shortener-api
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
    env_file:
      - ./back-end/.env
    command: sh -c "wait-for-it db:3306 -- npx drizzle-kit migrate && npm run start:prod"
    networks:
      - app-network

  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mysql-volume:
    driver: local

networks:
  app-network:
    driver: bridge
